GLOBAL_LIST_INIT(slasher_sounds, list(
	SOUND_ATTACK = list('necromorphs/sound/effects/creatures/necromorph/slasher/slasher_attack_1.ogg',
	'necromorphs/sound/effects/creatures/necromorph/slasher/slasher_attack_2.ogg',
	'necromorphs/sound/effects/creatures/necromorph/slasher/slasher_attack_3.ogg',
	'necromorphs/sound/effects/creatures/necromorph/slasher/slasher_attack_4.ogg',
	'necromorphs/sound/effects/creatures/necromorph/slasher/slasher_attack_5.ogg',
	'necromorphs/sound/effects/creatures/necromorph/slasher/slasher_attack_6.ogg',
	'necromorphs/sound/effects/creatures/necromorph/slasher/slasher_attack_7.ogg'),
	SOUND_DEATH = list('necromorphs/sound/effects/creatures/necromorph/slasher/slasher_death_1.ogg',
	'necromorphs/sound/effects/creatures/necromorph/slasher/slasher_death_2.ogg',
	'necromorphs/sound/effects/creatures/necromorph/slasher/slasher_death_3.ogg',
	'necromorphs/sound/effects/creatures/necromorph/slasher/slasher_death_4.ogg'),
	SOUND_PAIN = list('necromorphs/sound/effects/creatures/necromorph/slasher/slasher_pain_1.ogg',
	'necromorphs/sound/effects/creatures/necromorph/slasher/slasher_pain_2.ogg',
	'necromorphs/sound/effects/creatures/necromorph/slasher/slasher_pain_3.ogg',
	'necromorphs/sound/effects/creatures/necromorph/slasher/slasher_pain_4.ogg',
	'necromorphs/sound/effects/creatures/necromorph/slasher/slasher_pain_5.ogg',
	'necromorphs/sound/effects/creatures/necromorph/slasher/slasher_pain_6.ogg'),
	SOUND_SHOUT = list('necromorphs/sound/effects/creatures/necromorph/slasher/slasher_shout_1.ogg',
	'necromorphs/sound/effects/creatures/necromorph/slasher/slasher_shout_2.ogg',
	'necromorphs/sound/effects/creatures/necromorph/slasher/slasher_shout_3.ogg',
	'necromorphs/sound/effects/creatures/necromorph/slasher/slasher_shout_4.ogg'),
	SOUND_SHOUT_LONG = list('necromorphs/sound/effects/creatures/necromorph/slasher/slasher_shout_long_1.ogg',
	'necromorphs/sound/effects/creatures/necromorph/slasher/slasher_shout_long_2.ogg',
	'necromorphs/sound/effects/creatures/necromorph/slasher/slasher_shout_long_3.ogg',
	'necromorphs/sound/effects/creatures/necromorph/slasher/slasher_shout_long_4.ogg'),
	SOUND_SPEECH = list('necromorphs/sound/effects/creatures/necromorph/slasher/slasher_speech_1.ogg',
	'necromorphs/sound/effects/creatures/necromorph/slasher/slasher_speech_2.ogg')
))

GLOBAL_LIST_INIT(puker_sounds, list(
	SOUND_ATTACK = list('necromorphs/sound/effects/creatures/necromorph/puker/puker_attack_1.ogg',
	'necromorphs/sound/effects/creatures/necromorph/puker/puker_attack_2.ogg',
	'necromorphs/sound/effects/creatures/necromorph/puker/puker_attack_3.ogg',
	'necromorphs/sound/effects/creatures/necromorph/puker/puker_attack_4.ogg',
	'necromorphs/sound/effects/creatures/necromorph/puker/puker_attack_5.ogg'),
	SOUND_DEATH = list('necromorphs/sound/effects/creatures/necromorph/puker/puker_death_1.ogg',
	'necromorphs/sound/effects/creatures/necromorph/puker/puker_death_2.ogg',
	'necromorphs/sound/effects/creatures/necromorph/puker/puker_death_3.ogg'),
	SOUND_PAIN = list('necromorphs/sound/effects/creatures/necromorph/puker/puker_pain_1.ogg',
	'necromorphs/sound/effects/creatures/necromorph/puker/puker_pain_2.ogg',
	'necromorphs/sound/effects/creatures/necromorph/puker/puker_pain_3.ogg',
	'necromorphs/sound/effects/creatures/necromorph/puker/puker_pain_4.ogg',
	'necromorphs/sound/effects/creatures/necromorph/puker/puker_pain_5.ogg',
	'necromorphs/sound/effects/creatures/necromorph/puker/puker_pain_6.ogg',
	'necromorphs/sound/effects/creatures/necromorph/puker/puker_pain_7.ogg'),
	SOUND_SHOUT = list('necromorphs/sound/effects/creatures/necromorph/puker/puker_shout_1.ogg',
	'necromorphs/sound/effects/creatures/necromorph/puker/puker_shout_2.ogg',
	'necromorphs/sound/effects/creatures/necromorph/puker/puker_shout_3.ogg',
	'necromorphs/sound/effects/creatures/necromorph/puker/puker_shout_4.ogg',
	'necromorphs/sound/effects/creatures/necromorph/puker/puker_shout_5.ogg',
	'necromorphs/sound/effects/creatures/necromorph/puker/puker_shout_6.ogg'),
	SOUND_SHOUT_LONG = list('necromorphs/sound/effects/creatures/necromorph/puker/puker_shout_long_1.ogg',
	'necromorphs/sound/effects/creatures/necromorph/puker/puker_shout_long_2.ogg',
	'necromorphs/sound/effects/creatures/necromorph/puker/puker_shout_long_3.ogg',
	'necromorphs/sound/effects/creatures/necromorph/puker/puker_shout_long_4.ogg'),
	SOUND_SPEECH = list('necromorphs/sound/effects/creatures/necromorph/puker/puker_speech_1.ogg',
	'necromorphs/sound/effects/creatures/necromorph/puker/puker_speech_2.ogg',
	'necromorphs/sound/effects/creatures/necromorph/puker/puker_speech_3.ogg')
))

GLOBAL_LIST_INIT(spitter_sounds, list(
	SOUND_ATTACK = list('necromorphs/sound/effects/creatures/necromorph/spitter/spitter_attack_1.ogg',
	'necromorphs/sound/effects/creatures/necromorph/spitter/spitter_attack_2.ogg',
	'necromorphs/sound/effects/creatures/necromorph/spitter/spitter_attack_3.ogg',
	'necromorphs/sound/effects/creatures/necromorph/spitter/spitter_attack_4.ogg',
	'necromorphs/sound/effects/creatures/necromorph/spitter/spitter_attack_5.ogg',
	'necromorphs/sound/effects/creatures/necromorph/spitter/spitter_attack_6.ogg',
	'necromorphs/sound/effects/creatures/necromorph/spitter/spitter_attack_7.ogg',
	'necromorphs/sound/effects/creatures/necromorph/spitter/spitter_attack_8.ogg',
	'necromorphs/sound/effects/creatures/necromorph/spitter/spitter_attack_9.ogg',
	'necromorphs/sound/effects/creatures/necromorph/spitter/spitter_attack_extreme.ogg'),
	SOUND_DEATH = list('necromorphs/sound/effects/creatures/necromorph/spitter/spitter_death_1.ogg',
	'necromorphs/sound/effects/creatures/necromorph/spitter/spitter_death_2.ogg',
	'necromorphs/sound/effects/creatures/necromorph/spitter/spitter_death_3.ogg'),
	SOUND_PAIN = list('necromorphs/sound/effects/creatures/necromorph/spitter/spitter_pain_1.ogg',
	'necromorphs/sound/effects/creatures/necromorph/spitter/spitter_pain_2.ogg',
	'necromorphs/sound/effects/creatures/necromorph/spitter/spitter_pain_3.ogg',
	'necromorphs/sound/effects/creatures/necromorph/spitter/spitter_pain_4.ogg',
	'necromorphs/sound/effects/creatures/necromorph/spitter/spitter_pain_5.ogg',
	'necromorphs/sound/effects/creatures/necromorph/spitter/spitter_pain_6.ogg',
	'necromorphs/sound/effects/creatures/necromorph/spitter/spitter_pain_7.ogg',
	'necromorphs/sound/effects/creatures/necromorph/spitter/spitter_pain_8.ogg',
	'necromorphs/sound/effects/creatures/necromorph/spitter/spitter_pain_extreme.ogg',
	'necromorphs/sound/effects/creatures/necromorph/spitter/spitter_pain_extreme_2.ogg'),
	SOUND_SHOUT = list('necromorphs/sound/effects/creatures/necromorph/spitter/spitter_shout_1.ogg',
	'necromorphs/sound/effects/creatures/necromorph/spitter/spitter_shout_2.ogg',
	'necromorphs/sound/effects/creatures/necromorph/spitter/spitter_shout_3.ogg',
	'necromorphs/sound/effects/creatures/necromorph/spitter/spitter_shout_4.ogg'),
	SOUND_SHOUT_LONG = list('necromorphs/sound/effects/creatures/necromorph/spitter/spitter_shout_long_1.ogg',
	'necromorphs/sound/effects/creatures/necromorph/spitter/spitter_shout_long_2.ogg',
	'necromorphs/sound/effects/creatures/necromorph/spitter/spitter_shout_long_3.ogg',
	'necromorphs/sound/effects/creatures/necromorph/spitter/spitter_shout_long_4.ogg',
	'necromorphs/sound/effects/creatures/necromorph/spitter/spitter_shout_long_5.ogg'),
	SOUND_SPEECH = list('necromorphs/sound/effects/creatures/necromorph/spitter/spitter_speech_1.ogg',
	'necromorphs/sound/effects/creatures/necromorph/spitter/spitter_speech_2.ogg',
	'necromorphs/sound/effects/creatures/necromorph/spitter/spitter_speech_3.ogg',
	'necromorphs/sound/effects/creatures/necromorph/spitter/spitter_speech_4.ogg',
	'necromorphs/sound/effects/creatures/necromorph/spitter/spitter_speech_5.ogg')
))
